name: 检查上游更新

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: "2410"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 获取上游最新提交
        id: getHash
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
          echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: 对比已编译版本
        id: cacheHash
        uses: actions/cache@v4
        with:
          path: .commitHash
          key: commitHash_${{ steps.getHash.outputs.commitHash }}
      - name: 记录新版本号
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
      - name: 触发固件编译
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ github.token }}
          event-type: 上游更新